; Song New song in Lightweight format (V1).
; Generated by Arkos Tracker 2.

pfc_Start
pfc_StartDisarkGenerateExternalLabel

pfc_DisarkByteRegionStart0
	db "ATLW"	; Format marker (LightWeight).
	db 1	; Format version.
pfc_DisarkByteRegionEnd0
pfc_DisarkPointerRegionStart1
	dw pfc_FmInstrumentTable
	dw pfc_ArpeggioTable
	dw pfc_PitchTable
; Table of the Subsongs.
	dw pfc_Subsong0
pfc_DisarkPointerRegionEnd1

; The Arpeggio table.
pfc_ArpeggioTable
pfc_DisarkWordRegionStart2
	dw 0
pfc_DisarkWordRegionEnd2
pfc_DisarkPointerRegionStart3
pfc_DisarkPointerRegionEnd3

; The Pitch table.
pfc_PitchTable
pfc_DisarkWordRegionStart4
	dw 0
pfc_DisarkWordRegionEnd4
pfc_DisarkPointerRegionStart5
pfc_DisarkPointerRegionEnd5

; The FM Instrument table.
pfc_FmInstrumentTable
pfc_DisarkPointerRegionStart6
	dw pfc_FmInstrument0
	dw pfc_FmInstrument1
	dw pfc_FmInstrument2
	dw pfc_FmInstrument3
pfc_DisarkPointerRegionEnd6

pfc_DisarkByteRegionStart7
pfc_FmInstrument0
	db 255	; Speed.

pfc_FmInstrument0Loop	db 0	; Volume: 0.

	db 4	; End the instrument.
pfc_DisarkPointerRegionStart8
	dw pfc_FmInstrument0Loop	; Loops.
pfc_DisarkPointerRegionEnd8

pfc_FmInstrument1
	db 0	; Speed.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 61	; Volume: 15.

	db 4	; End the instrument.
pfc_DisarkPointerRegionStart9
	dw pfc_FmInstrument0Loop	; Loop to silence.
pfc_DisarkPointerRegionEnd9

pfc_FmInstrument2
	db 0	; Speed.

	db 189	; Volume: 15.
	db 25	; Arpeggio: 12.
	db 11	; Noise: 11.

	db 185	; Volume: 14.
	db 27	; Arpeggio: 13.
	db 10	; Noise: 10.

	db 181	; Volume: 13.
	db 33	; Arpeggio: 16.
	db 9	; Noise: 9.

	db 181	; Volume: 13.
	db 19	; Arpeggio: 9.
	db 8	; Noise: 8.

	db 177	; Volume: 12.
	db 1	; Arpeggio: 0.
	db 7	; Noise: 7.

	db 169	; Volume: 10.
	db 19	; Arpeggio: 9.
	db 6	; Noise: 6.

	db 161	; Volume: 8.
	db 29	; Arpeggio: 14.
	db 5	; Noise: 5.

	db 153	; Volume: 6.
	db 1	; Arpeggio: 0.
	db 4	; Noise: 4.

	db 145	; Volume: 4.
	db 1	; Arpeggio: 0.
	db 3	; Noise: 3.

	db 141	; Volume: 3.
	db 1	; Arpeggio: 0.
	db 2	; Noise: 2.

	db 4	; End the instrument.
pfc_DisarkPointerRegionStart10
	dw pfc_FmInstrument0Loop	; Loop to silence.
pfc_DisarkPointerRegionEnd10

pfc_FmInstrument3
	db 0	; Speed.

	db 61	; Volume: 15.

	db 4	; End the instrument.
pfc_DisarkPointerRegionStart11
	dw pfc_FmInstrument0Loop	; Loop to silence.
pfc_DisarkPointerRegionEnd11

pfc_DisarkByteRegionEnd7
pfc_Subsong0DisarkByteRegionStart0
; Song New song, Subsong 0 - Main - in Lightweight format (V1).
; Generated by Arkos Tracker 2.

pfc_Subsong0
	db 4	; Initial speed.

; The Linker.
; Pattern 0
pfc_Subsong0loop
	db 5	; State byte.
	db 63	; New height.
pfc_Subsong0DisarkPointerRegionStart1
	dw pfc_Subsong0_Track0, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd1
; The tracks.

; Pattern 1
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart2
	dw pfc_Subsong0_Track2, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd2
; The tracks.

; Pattern 2
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart3
	dw pfc_Subsong0_Track3, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd3
; The tracks.

; Pattern 3
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart4
	dw pfc_Subsong0_Track4, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd4
; The tracks.

; Pattern 4
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart5
	dw pfc_Subsong0_Track5, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd5
; The tracks.

; Pattern 5
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart6
	dw pfc_Subsong0_Track6, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd6
; The tracks.

; Pattern 6
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart7
	dw pfc_Subsong0_Track7, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd7
; The tracks.

; Pattern 7
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart8
	dw pfc_Subsong0_Track8, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd8
; The tracks.

; Pattern 8
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart9
	dw pfc_Subsong0_Track9, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd9
; The tracks.

; Pattern 9
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart10
	dw pfc_Subsong0_Track10, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd10
; The tracks.

; Pattern 10
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart11
	dw pfc_Subsong0_Track11, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd11
; The tracks.

; Pattern 11
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart12
	dw pfc_Subsong0_Track12, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd12
; The tracks.

; Pattern 12
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart13
	dw pfc_Subsong0_Track13, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd13
; The tracks.

; Pattern 13
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart14
	dw pfc_Subsong0_Track14, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd14
; The tracks.

; Pattern 14
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart15
	dw pfc_Subsong0_Track15, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd15
; The tracks.

; Pattern 15
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart16
	dw pfc_Subsong0_Track16, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd16
; The tracks.

; Pattern 16
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart17
	dw pfc_Subsong0_Track9, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd17
; The tracks.

; Pattern 17
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart18
	dw pfc_Subsong0_Track10, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd18
; The tracks.

; Pattern 18
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart19
	dw pfc_Subsong0_Track11, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd19
; The tracks.

; Pattern 19
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart20
	dw pfc_Subsong0_Track12, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd20
; The tracks.

; Pattern 20
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart21
	dw pfc_Subsong0_Track17, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd21
; The tracks.

; Pattern 21
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart22
	dw pfc_Subsong0_Track18, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd22
; The tracks.

; Pattern 22
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart23
	dw pfc_Subsong0_Track19, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd23
; The tracks.

; Pattern 23
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart24
	dw pfc_Subsong0_Track20, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd24
; The tracks.

; Pattern 24
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart25
	dw pfc_Subsong0_Track21, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd25
; The tracks.

; Pattern 25
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart26
	dw pfc_Subsong0_Track22, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd26
; The tracks.

; Pattern 26
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart27
	dw pfc_Subsong0_Track23, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd27
; The tracks.

; Pattern 27
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart28
	dw pfc_Subsong0_Track24, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd28
; The tracks.

; Pattern 28
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart29
	dw pfc_Subsong0_Track17, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd29
; The tracks.

; Pattern 29
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart30
	dw pfc_Subsong0_Track18, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd30
; The tracks.

; Pattern 30
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart31
	dw pfc_Subsong0_Track19, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd31
; The tracks.

; Pattern 31
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart32
	dw pfc_Subsong0_Track20, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd32
; The tracks.

; Pattern 32
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart33
	dw pfc_Subsong0_Track25, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd33
; The tracks.

; Pattern 33
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart34
	dw pfc_Subsong0_Track26, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd34
; The tracks.

; Pattern 34
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart35
	dw pfc_Subsong0_Track27, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd35
; The tracks.

; Pattern 35
	db 1	; State byte.
pfc_Subsong0DisarkPointerRegionStart36
	dw pfc_Subsong0_Track28, pfc_Subsong0_Track1, pfc_Subsong0_Track1
pfc_Subsong0DisarkPointerRegionEnd36
; The tracks.

	db 0	; End of the subsong.
pfc_Subsong0DisarkPointerRegionStart37
	dw pfc_Subsong0loop
pfc_Subsong0DisarkPointerRegionEnd37

; The Tracks.
pfc_Subsong0_Track0
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.

pfc_Subsong0_Track1
	db 61, 63	; Long wait: 64.


pfc_Subsong0_Track2
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.

pfc_Subsong0_Track3
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.

pfc_Subsong0_Track4
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 254	; Short wait: 4.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 9	; Note: 33.
	db 62	; Short wait: 1.


pfc_Subsong0_Track5
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 41	; Note: 65.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.

pfc_Subsong0_Track6
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 63, 72	; Escaped note: 72.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


pfc_Subsong0_Track7
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 39	; Note: 63.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 46	; Note: 70.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.

pfc_Subsong0_Track8
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 63, 75	; Escaped note: 75.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 41	; Note: 65.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 46	; Note: 70.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.

pfc_Subsong0_Track9
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 29	; Note: 53.
	db 29	; Note: 53.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 29	; Note: 53.
	db 29	; Note: 53.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.

pfc_Subsong0_Track10
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 32	; Note: 56.
	db 32	; Note: 56.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 34	; Note: 58.
	db 34	; Note: 58.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.

pfc_Subsong0_Track11
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 36	; Note: 60.
	db 36	; Note: 60.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 32	; Note: 56.
	db 32	; Note: 56.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 126	; Short wait: 2.

	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.

pfc_Subsong0_Track12
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 34	; Note: 58.
	db 34	; Note: 58.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 34	; Note: 58.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 29	; Note: 53.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 27	; Note: 51.
	db 27	; Note: 51.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 9	; Note: 33.

pfc_Subsong0_Track13
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 41	; Note: 65.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 46	; Note: 70.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 72	; Escaped note: 72.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 77	; Escaped note: 77.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 44	; Note: 68.
	db 46	; Note: 70.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


pfc_Subsong0_Track14
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 80	; Escaped note: 80.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 82	; Escaped note: 82.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 63, 75	; Escaped note: 75.
	db 63, 72	; Escaped note: 72.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 12	; Note: 36.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 0	; Note: 24.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 75	; Escaped note: 75.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 63, 75	; Escaped note: 75.
	db 63, 77	; Escaped note: 77.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.


pfc_Subsong0_Track15
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 84	; Escaped note: 84.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 8	; Note: 32.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 63, 20	; Escaped note: 20.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 75	; Escaped note: 75.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 63, 77	; Escaped note: 77.
	db 63, 80	; Escaped note: 80.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 15	; Note: 39.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 3	; Note: 27.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 84	; Escaped note: 84.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 63, 77	; Escaped note: 77.
	db 63, 80	; Escaped note: 80.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.

pfc_Subsong0_Track16
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 63, 77	; Escaped note: 77.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 5	; Note: 29.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 190	; Short wait: 3.

	db 63, 72	; Escaped note: 72.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 39	; Note: 63.
	db 41	; Note: 65.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 62	; Short wait: 1.

	db 41	; Note: 65.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 17	; Note: 41.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 62	; Short wait: 1.

	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 126	; Short wait: 2.

	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 62	; Short wait: 1.

	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.

pfc_Subsong0_Track17
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.

pfc_Subsong0_Track18
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 174	; Note: 70.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.

pfc_Subsong0_Track19
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.

pfc_Subsong0_Track20
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 84	; Escaped note: 84.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 80	; Escaped note: 80.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 191, 82	; Escaped note: 82.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 191, 75	; Escaped note: 75.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 191, 77	; Escaped note: 77.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 191, 72	; Escaped note: 72.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 9	; Note: 33.

pfc_Subsong0_Track21
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.

pfc_Subsong0_Track22
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.

pfc_Subsong0_Track23
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 148	; Note: 44.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.

pfc_Subsong0_Track24
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 9	; Note: 33.

pfc_Subsong0_Track25
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 150	; Note: 46.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 4	; New instrument: 2.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.

pfc_Subsong0_Track26
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 128	; Note: 24.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 135	; Note: 31.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.

pfc_Subsong0_Track27
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 191, 20	; Escaped note: 20.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 136	; Note: 32.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 152	; Note: 48.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 140	; Note: 36.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.

pfc_Subsong0_Track28
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 143	; Note: 39.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 155	; Note: 51.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 157	; Note: 53.
	db 6	; New instrument: 3.
	db 145	; Note: 41.
	db 2	; New instrument: 1.
	db 160	; Note: 56.
	db 6	; New instrument: 3.
	db 152	; Note: 48.
	db 0	; New instrument: 0.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 131	; Note: 27.
	db 2	; New instrument: 1.
	db 167	; Note: 63.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 169	; Note: 65.
	db 6	; New instrument: 3.
	db 138	; Note: 34.
	db 2	; New instrument: 1.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 172	; Note: 68.
	db 6	; New instrument: 3.
	db 133	; Note: 29.
	db 2	; New instrument: 1.
	db 162	; Note: 58.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 164	; Note: 60.
	db 6	; New instrument: 3.
	db 137	; Note: 33.
	db 4	; New instrument: 2.
	db 9	; Note: 33.

pfc_Subsong0DisarkByteRegionEnd0
